app:
  env: 'production'
  secret_key: 'my secret key'
  debug: true
  host: '0.0.0.0'
  port: 8000
  sqlalchemy_track_modifications: True

db:
  driver: 'postgresql'
  host: 'postgres'
  port: '5432'
  username: 'postgres'
  password: 'postgres'
  name: 'mydb'