version: '3'
services:
  db:
    hostname: postgres
    image: postgres:12.5
    restart: on-failure
    volumes:
      - /media/postgres/data:/var/lib/postgresql/data
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - LOG_LEVEL=ERROR
    ports:
      - "5432:5432"
  todos-service:
    image: todos-flask:0.1.2
    environment:
      - CONFIG_PATH=/application.yml
    command: gunicorn todos_app.wsgi:app -w 1 --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./application.yml:/application.yml
    ports:
      - "8000:8000"
